# Generated by Django 3.2.7 on 2021-09-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('thum', models.ImageField(blank=True, null=True, upload_to='')),
                ('deskripsi', models.TextField(max_length=255)),
                ('categories', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
        ),
    ]
