# Generated by Django 3.2.7 on 2021-09-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thum',
            new_name='thumb',
        ),
    ]
