# Generated by Django 3.2.7 on 2021-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='django.utils.timezone', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
